apiVersion: v1
kind: Service
metadata:
  name: go-multiplication
  namespace: polyglot
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      name: port8080
      port: 8080
      protocol: TCP
  selector:
    app: go-multiplication